name: Deploy to Firebase Hosting on merge

concurrency:
  group: production
  cancel-in-progress: true

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm
      - run: pnpm install --no-frozen-lockfile
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          IMG_CDN_PUBLIC_KEY: ${{ secrets.IMG_CDN_PUBLIC_KEY }}
          IMG_CDN_URL_ENDPOINT: ${{ secrets.IMG_CDN_URL_ENDPOINT }}
          IMG_CDN_AUTH_ENDPOINT: ${{ secrets.IMG_CDN_AUTH_ENDPOINT }}
          FIRESTORE_API_KEY: ${{ secrets.FIRESTORE_API_KEY }}
          FIRESTORE_AUTH_DOMAIN: ${{ secrets.FIRESTORE_AUTH_DOMAIN }}
          FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
          FIRESTORE_STORAGE_BUCKET: ${{ secrets.FIRESTORE_STORAGE_BUCKET }}
          FIRESTORE_SENDER_ID: ${{ secrets.FIRESTORE_SENDER_ID }}
          FIRESTORE_APP_ID: ${{ secrets.FIRESTORE_APP_ID }}
          FIRESTORE_MEASUREMENT_ID: ${{ secrets.FIRESTORE_MEASUREMENT_ID }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      - run: pnpm -F ui config:env
      - run: pnpm -F ui build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NG_AFPSICOLOGIA }}'
          channelId: live
          projectId: ng-afpsicologia
          publicRoot: 'ui/dist'
